# This is an example docker-compose file to run both the skill service and it's corresponding database on your
# machine locally
# For production use, please replace the passwords with suitable passwords.
version: '3.7'
services:
  pwr-skill-service:
    image: pwr-skill-service:local
    ports:
      - 9003:9003
    environment:
      DB_USER: pwr-skill-service
      DB_PASS: changeit
      DB_URL: jdbc:mariadb://pwr_skill_service_db:3306/skill
      DB_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      DB_HIBERNATE_DDL_AUTO: update
      EUREKA_ENABLED: 'true'
      # Assuming usage of the default docker-compose file provided with discovery.
      # Change if necessary
      EUREKA_URL: http://host.docker.internal:8761/eureka
    depends_on:
      - pwr_skill_service_db
  pwr_skill_service_db:
    image: mariadb:latest
    restart: always
    ports:
      - 10003:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeit
      MYSQL_DATABASE: skill
      MYSQL_USER: pwr-skill-service
      MYSQL_PASSWORD: changeit
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: {}
