spring:
  application:
    name: pwr-skill-service
  datasource:
    url: jdbc:mysql://localhost:3306/skill
    username: skill
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 9003
management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
      base-path: /meta
---
spring:
  profiles: bootstrapDatabase
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: skill
    password: secret
    url: jdbc:mysql://localhost:3306/skill?useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    enabled: false
---
spring:
  profiles: localDev
  datasource:
    username: skill
    password: secret
    url: jdbc:mysql://localhost:3306/skill
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  config: ./logback.xml
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  profiles: localDevNoEureka
  datasource:
    username: skill
    password: secret
    url: jdbc:mysql://localhost:3306/skill?useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
logging:
  config: ./logback.xml
eureka:
  client:
    enabled: false
---
spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:datajpa
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    enabled: false